stages:
  - build

variables:
  MAVEN_OPTS: "-Xmx2g -XX:ReservedCodeCacheSize=512m"
  JAVA_VERSION_MAJOR: "7"

build-app:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
    - target/*-jar-with-dependencies.jar
  only:
    - master
  image: gitlab-registry.cern.ch/awg/spark:base-j${JAVA_VERSION_MAJOR}
